# Generated by Django 4.2.5 on 2023-09-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bloger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='fecha')),
                ('upload', models.FileField(upload_to='bloger/img')),
            ],
        ),
    ]
