# Generated by Django 4.2.5 on 2023-09-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('precio', models.IntegerField()),
                ('total', models.IntegerField()),
                ('upload', models.FileField(upload_to='bloger/product')),
            ],
        ),
    ]
